alphagov/contacts-admin

- README.md
- config/environments/development.rb
Reduces complexity.
If integration with Rummager were to be broken, we want to know before we deploy
it to preview/production.
The comment about WHITEHALL_API was out of date.
> Use Rummager in development

- Gemfile
- Gemfile.lock
These lines make the log really noisy. We use it successfully in quite a few apps: https://github.com/search?q=user%3Aalphagov+quiet_assets&type=Code&utf8=%E2%9C%93
> Disable asset request logging in dev

- app/value_objects/contacts_search.rb
- app/views/admin/contacts/_search_form.html.erb
- app/views/contacts/index.html.erb
- spec/features/admin/contact_filter_spec.rb
- spec/features/steps/admin/contact_steps.rb
Filtering by organisation wasn't working at all.
Searching was doing an exact match so was very hard to use.
I've copied the rspec features style from https://github.com/alphagov/manuals-frontend/pull/76. I hope to rewrite all of the features to this style shortly.
Fixes https://github.com/alphagov/hmrc-contacts/issues/171
> Fix admin filtering

- app/controllers/admin/contacts_controller.rb
Both related entities were being loaded individually. This change improves the
page load time and reduces the number of queries to the database.
> Eager load Groups & Organisations for contacts

- app/controllers/admin_controller.rb
- config/environments/development.rb
- config/environments/production.rb
Setting the asset_host to nil in the admin controller was intended to only
apply to admin, but actually applied to frontend too. This meant that in
production-like environments, the links to stylesheets didn't work.
I copied the technique from here:
http://stackoverflow.com/a/10252239
> Fix broken frontend assets

- app/interactors/admin/destroy_contact.rb
- spec/features/admin/contact_removal_spec.rb
- spec/features/steps/admin/site_search_steps.rb
The code for deleting items from GOV.UK site search wouldn't have worked because it was using the slug. Rummager needs the path to the item, omitting the leading slash.
This hasn't been an issue for contacts, because they aren't added to the site search index.
Theoretically, it could have deleted mainstream content from search where the slugs collided, but a review of the contacts that have been deleted indicates this hasn't happened.
> Fix removing from site search

- app/controllers/contacts_controller.rb
- spec/features/public/contacts_index_spec.rb
This issue is causing significant number of errors in production.
I renamed the search parameter in c439191e5bf24366fdfc961dcd7f162de0f09497
Unfortunately, many links exist which use the old parameter name, and when the
old parameter name is supplied, Searchlight raises an error.
The alternatives to this would be:
* revert the changes, go back to the old name and hope users don't bookmark the
new name
* discard the old parameter
* redirect requests to use the new parameter
> Fix "old" search links

- app/presenters/contacts_finder_presenter.rb
- app/tasks/import_organisations.rb
- db/migrate/20150114102401_add_content_id_to_organisations.rb
- db/schema.rb
- lib/tasks/finders.rake
Relies on https://github.com/alphagov/contacts-admin/pull/183 and https://github.com/alphagov/whitehall/pull/1950 being merged first.
This PR contains the work necessary to tag Org Contacts Finders to the correct Org. It does this by retrieving the content_id from the Whitehall Org API and sending it to the Publishing API with the Contacts Finder Content Item.
> Org contact id for finders & rake task for publishing Finders.

- app/models/contact_group.rb
Publishing the Finder will take over the Index page for Contacts and as they don't yet exist in the search index there's then no way to browse them.
This commit disables the Finder publishing temporarily by commenting it out and explaining why it is commented.
> Disable Finder publishing for now

- db/migrate/20150112114049_add_unique_constraint_to_organisation_slugs.rb
- db/schema.rb
For the index to be created, the every value in the field has to be unique, so
we need to deduplicate the field first.
> Prevent duplicate organisations being created

- jenkins.sh
- spec/spec_helper.rb
Only generate it on CI build, or if run with COVERAGE=on.
Generating the coverage files takes a non-trivial time after a successful run
of the test suite, which can be annoying if you want to get on with running
another command.
Copied from: https://github.com/alphagov/content-store/pull/102 and the simplecov-rcov documentation: https://github.com/fguillen/simplecov-rcov#usage
> Don't generate rcov coverage data by default

- lib/tasks/update_organisation_slug.rake
- On second-line while running each of the rake tasks within each of
the apps as per the guide to change an organisation slug, we came
across this one that didn't work. Fix it by referencing
`args.old_slug` etc, because they come from command-line arguments.
> Fix `undefined local variable` errors in the update org slugs rake task

- app/presenters/contacts_finder_presenter.rb
As Finder Frontend becomes more generic, we want to be able to specify how we restrict the default filter. This commit adds it to the content item when it is published. We also move the `document_type` into the `filter` as `filter_document_type`. This PR relates to the work in https://github.com/alphagov/finder-frontend/pull/161.
> Finder filter restriction in content item

- app/presenters/contacts_finder_presenter.rb
With the changes in Finder Frontend to remove all the format specific code, Contacts won't have any facets. This change sets the new attrs of `filterable` and `display_as_result_metadata` for the Topic facet. 
Don't merge before https://github.com/alphagov/finder-frontend/pull/148.
> Use new facet structure

- Gemfile
- Gemfile.lock
- README.md
- app/presenters/contacts_finder_presenter.rb
- jenkins-schema.sh
- jenkins.sh
- spec/presenters/contacts_finder_presenter_spec.rb
- spec/support/govuk_content_schema_helpers.rb
This is largely copied from Whitehall.
We plan to work out a way of sharing the Ruby code, but a little bit of duplication feels sensible at this stage.
Once contacts are defined in govuk-content-schemas, they can be tested too.
> govuk-content-schema tests for finders

- app/presenters/contacts_finder_presenter.rb
There's no point always sending empty arrays to publishing API for fields
which are optional.
> Don't send empty arrays to publishing API

- spec/presenters/contact_form_links_presenter_spec.rb
- spec/presenters/contact_groups_presenter_spec.rb
- spec/presenters/email_addresses_presenter_spec.rb
- spec/presenters/phone_numbers_presenter_spec.rb
- spec/presenters/post_addresses_presenter_spec.rb
These specs behave differently, depending on which version of the parsing
library is used by Nokogiri. These libraries vary depending on the version
of Ubuntu running on the system, meaning that govspeak fields can have
extra whitespace or newlines.
/cc @fofr
> Make specs involving govspeak less flaky

- app/views/contacts/index.html.erb
- app/views/layouts/application.html.erb
- spec/features/public/contacts_index_spec.rb
Part of improving search result snipperts shown on external search
engines.
The lack of a meta-description tag makes some search result snippets
unhelpful, confusing, or misleading. Ticket:
https://trello.com/c/S6VUwRWQ/273-follow-up-add-meta-description-tag-to-custom-content-types
> Add meta description tag to contact index page

- app/models/contact.rb
- spec/features/steps/admin/site_search_steps.rb
- spec/models/contact_spec.rb
`last_update`  and `public_timestamp` mean the same thing in rummager.
Current behaviour of rummager is that if `public_timestamp` is empty, `last_update` [gets copied into `public_timestamp`](https://github.com/alphagov/rummager/blob/d3637f348612b76ee4de8d2c01048af39ea2a568/lib/indexer/document_preparer.rb#L46).
This commit changes what is sent to rummager so that we populate `public_timestamp` directly and can remove the special field and special code from rummager.
Trello: https://trello.com/c/yY2jFlXl
Previous PRs: https://github.com/alphagov/hmrc-manuals-api/pull/106 & https://github.com/alphagov/specialist-publisher/pull/545
> Send `public_timestamp` to rummager

- app/interactors/admin/destroy_and_redirect_contact.rb
- app/presenters/contact_gone_presenter.rb
- app/presenters/contact_redirect_presenter.rb
- lib/redirector_for_gone_contact.rb
- lib/tasks/contacts.rake
- spec/interactors/admin/destroy_and_redirect_contact_spec.rb
- spec/lib/redirector_for_gone_contact_spec.rb
- spec/presenters/contact_gone_presenter_spec.rb
- spec/presenters/contact_redirect_presenter_spec.rb
For: https://trello.com/c/SAGyyLlH/192-delete-and-redirect-two-hmrc-contact-records
We have to deal with 2 contacts that need to be redirected to somewhere else.  The first still exists and that is what `rake contacts:remove_with_redirect` is for - we remove the contact and publish a new redirect item in the content store to replace it.  The second has already been deleted and that is what `rake contacts:replace_gone_with_redirect` is for - we check that the contact really is "gone" and if so replace that with a redirect item.
These are the only requests we've had so far, so there's no need to make this part of the web UI - although if we ever do, we'd want to support the first form rather than the second.  To that end, the bulk of the implementation of `rake …
> Scripts for redirecting gone contacts

- lib/redirector_for_gone_contact.rb
- spec/lib/redirector_for_gone_contact_spec.rb
We were being super cautious and making sure that the publishing_app of a
removed contact was `contacts-admin` and not publishing the redirect if it
wasn't.  However, the representation of a content-item that you get from
the content-store api doesn't include the publishing_app because
content-store provides frontend representations of items and the
publishing_app is really a backend concern.
We're fairly sure this will be ok because we don't let you jsut redirect
any path, it's a constructed path for a contact object and only
contacts-admin would publish those paths.
> Don't check publishing_app before redirecting

- app/tasks/seed_database.rb
The [README](https://github.com/alphagov/contacts-admin/blob/master/README.md) states to do the following for setting up the local database:
```
bundle exec rake db:schema:load
bundle exec rake db:seed
bundle exec rake contacts:import_hmrc DATA_FILE=db/contact-records.csv
```
This fails with a clean local install, because an organisation with the slug 'hm-revenue-customs' is being created twice (so fails with `ActiveRecord::RecordNotUnique`).
This is because we already import all organisation from Whitehall [here](https://github.com/alphagov/contacts-admin/blob/aaabd12a8ec02be12f18a2604ecd1ac59924bb20/db/seeds.rb#L2) as part of the seed. To fix, we only create it if it does not exist.
> Create 'hmrc' organisation only if it does not exist

- app/models/contact.rb
- app/presenters/contact_groups_presenter.rb
- app/presenters/contact_organisation_presenter.rb
- app/presenters/contact_presenter.rb
- app/presenters/contact_rummager_presenter.rb
- app/tasks/import_organisations.rb
- db/migrate/20151211163428_add_content_id_to_organisations.rb
- db/schema.rb
- jenkins-schema.sh
- spec/features/steps/admin/site_search_steps.rb
- spec/models/contact_spec.rb
- spec/presenters/contact_groups_presenter_spec.rb
- spec/presenters/contact_presenter_spec.rb
- spec/presenters/contact_rummager_presenter_spec.rb
This PR implements contract testing for the newly defined `contact` content schema (https://github.com/alphagov/govuk-content-schemas/pull/167). We follow the 'how-to' docs from govuk-content-schema (https://github.com/alphagov/govuk-content-schemas/blob/master/docs/contract-testing-howto.md)
We move out any code that generates JSON to separate presenters in order to be more consistent with the rest of the app and make more obvious to see which attributes are being exported as JSON.
We also add the contact's organisation `content_id` to the `links` hash so that we can access the organisation in the `content-store`. We do not remove organisation data from the `details` hash yet because in `contacts-frontend` we require the `organisation.abbreviation` attribute, which is currently not …
> Add contracts tests for content schema

- jenkins-schema.sh
This should fix the Jenkins schema build.
I created a temporary Jenkins job for this branch. The build passed, so I think that should fix it.
https://ci.dev.publishing.service.gov.uk/job/govuk_contacts_admin_schema_tests-TEMPORARY/1/console
> Fix the govuk-content-schema tests on Jenkins

- app/presenters/contacts_finder_presenter.rb
- lib/tasks/publishing_api.rake
This was being sent as "contacts" for the detail pages but "contacts-admin" for the index. (Note that contacts_finder_presenter is not currently used anywhere, but also needs the same value for when it is eventually implemented.)
> Make publishing_app value consistent.

- app/models/contact.rb
- lib/tasks/contacts.rake
- spec/factories/organisations.rb
- spec/presenters/contact_presenter_spec.rb
- Before this change, this app imported organisations from `whitehall` and
exported this data as part of the `details` hash to the content-store.
(Organisations are represented in the `content-store` under the format
of `placeholder_organisation` and only contain a subset of the
`whitehall` organisation attributes.)
- After this change, the import stays the same, but we can send
organisation data in the links hash because the frontend will soon
no longer use `organisation.abbreviation`, which makes it consistent
with the general patterns for referring to organisations in the new
world - from the content-store, with just a `content_id`.
- Follows on from 6ec8af.
- Amend the Register rake task into one to Republish contacts, which we'll need to run when we deploy this change and again when …
> Send the organisation data in the links hash for a contact

- app/views/admin/contacts/_search_form.html.erb
- Fixes #169 after just over a year!
- This now stays at a decent size with and without JavaScript on. I
chose `input-md-5` out of thin air, but most of the org titles now
display fine in the dropdown, and it's better than it was!
Before:
After:
> Make the organisation filter a decent size for the values within it

- lib/tasks/publishing_api.rake
This makes the Publishing API payload consistent with all the other
pages within this app.
/cc @issyl0 @jennyd
> Publishing API: add organisation link for HMRC index page

- app/presenters/contact_presenter.rb
- spec/presenters/contact_presenter_spec.rb
- This needs to be removed as the frontend now picks up `organisation`
from the links hash, not the details hash (https://github.com/alphagov/contacts-frontend/pull/41). This was only kept in here
so that we didn't have to faff around changing too much stuff and
potentially confusing things at deploy-time for #219. This tidies up.
Note: We'll need to run the Republish Contacts Rake task on deploy, so that details no longer have `organisations` in them.
Trello: https://trello.com/c/HEB3ukuP/263-remove-organisations-from-details-hash-for-contacts, related to https://trello.com/c/lIuKYwFE/235-use-the-full-organisation-name-instead-of-the-abbrevation-to-simplify-the-schemas-and-admin-tool.
> Remove the organisation data from the `details` hash

- app/interactors/admin/destroy_and_redirect_contact.rb
- app/interactors/admin/destroy_contact.rb
- app/models/contact.rb
- app/models/world_location.rb
- config/application.rb
- lib/publisher.rb
- lib/services.rb
- lib/tasks/publishing_api.rake
- spec/interactors/admin/destroy_and_redirect_contact_spec.rb
This is a convention that's prevalent across several other GOVUK apps,
particularly those that have been migrated to the new tagging
architecture and the V2 publishing API (see collections-publisher and
policy-publisher, for example).
> Access remote services via a Services module

- Gemfile
- Gemfile.lock
- spec/features/admin/contact_edit_spec.rb
- spec/features/steps/admin/publishing_api_steps.rb
- spec/interactors/admin/destroy_contact_spec.rb
When gds-api-adapters was bumped to version 27.0.0 (https://github.com/alphagov/gds-api-adapters/pull/417) it included changes to the test helpers of Publishing API V2 (https://github.com/alphagov/gds-api-adapters/pull/416), those changes broken 3 specs, reading @gpeng fixes (https://github.com/alphagov/whitehall/pull/2429/files#diff-69c5d68679b4279731fb962947d0bd31R148) I noticed that we now need to include a new method `request_json_includes` when `assert_publishing_api_put_content`.
After fixing this we are now able to upgrade to the current `gds-api-adapter`.
> Upgrades gds-api-adapters to 28.1.0

- app/controllers/admin/contacts_controller.rb
- app/interactors/admin/clone_contact.rb
- app/interactors/admin/create_contact.rb
- app/models/contact.rb
- app/presenters/contact_presenter.rb
- app/views/admin/contacts/_form.html.erb
- spec/features/admin/contact_clone_spec.rb
- spec/features/admin/contact_create_spec.rb
- spec/models/contact_spec.rb
- spec/presenters/contact_presenter_spec.rb
Finding Things is "migrating" the [tagging for all applications](https://trello.com/c/A4P3V9gK). Migration means that publisher apps should read & write the links hash from the publishing-api. This allows pages to be tagged by multiple apps. For example, a Whitehall document will be taggable in Whitehall, content-tagger and (in the future) a bulk-tagger application. Instead of the publisher apps having knowledge of the tags in their database, we have it centrally stored in the publishing-api.
Specifically for this application, it means that we should read & write the `organisations` links field from the publishing-api.
Originally, we wanted to refactor this app so that the organisation-dropdown for Contact is populated from the publishing-api and not saved in the database (#230). This …
> Send organisations link at creation

- lib/publisher.rb
- spec/lib/publisher_spec.rb
The publishing-api client expects a positional parameter, not an option, for the update_type on publish.
Log any errors with Errbit rather than swallowing silently.
> Pass correct publish params, and log errors.

- app/presenters/contact_gone_presenter.rb
- app/presenters/contact_presenter.rb
- app/presenters/contact_redirect_presenter.rb
- lib/publisher.rb
- spec/features/steps/admin/publishing_api_steps.rb
- spec/lib/publisher_spec.rb
- spec/presenters/contact_gone_presenter_spec.rb
- spec/presenters/contact_presenter_spec.rb
- spec/presenters/contact_redirect_presenter_spec.rb
`update_type` is supposed to be sent as an argument to the `publish` action.
Part of: https://github.com/alphagov/govuk-content-schemas/pull/259
> Don't send update_type in content payload

- db/migrate/20160420132844_remove_appointed_person_for_england_and_wales_organisation.rb
- db/schema.rb
This org was created in error and we are removing it.  The traffic is very low so we're not issuing a 410, just removing it (it should never have existed so a 404 is really what we want).
This is PR 4 of 5 for removing this org.
For more detail: https://trello.com/c/jbImjyLP/359-delete-an-org-page-5
> Migration to remove an org created in error

- app/views/layouts/application.html.erb
`role="breadcrumbs"` is not a thing.
https://www.w3.org/TR/wai-aria/roles#role_definitions
We previously removed from the component:
https://github.com/alphagov/static/pull/737
> Remove invalid breadcrumbs aria role

- app/presenters/contact_presenter.rb
The Contact model uses the organisation to determine its base path, for this reason,
we decided not to send the organisation data to publishing-api here but only on creation.
- Users can only select the organisation for the contact on creation
- After creation, we send the organisation to the publishing-api once
This means that if the  in the links is modified, contacts-admin will not
accidentally overwrite it - and we can start tagging contact pages with content-tagger.
See: https://github.com/alphagov/contacts-admin/pull/231.
> Specify why we're not sending orgs to pub-api

- app/presenters/contact_rummager_presenter.rb
- spec/presenters/contact_rummager_presenter_spec.rb
Blocked by:
https://github.com/alphagov/contacts-admin/pull/240
The work in the PR above needs to be deployed, after that the task to republish all contacts should be run (`rake contacts:republish`).
Why?:
Rummager has recently been updated to fetch links data directly from the
publishing API when indexing a document. Setting Rummager links data in
the publishing app is therefore redundant.
Ticket: https://trello.com/c/A4P3V9gK/414-mission-new-simplified-tagging-architecture
> Remove organisation link from Rummager payload

- app/presenters/contact_gone_presenter.rb
- app/presenters/contact_presenter.rb
- app/presenters/contact_redirect_presenter.rb
- spec/features/steps/admin/publishing_api_steps.rb
- spec/lib/redirector_for_gone_contact_spec.rb
- spec/presenters/contact_gone_presenter_spec.rb
- spec/presenters/contact_redirect_presenter_spec.rb
`document_type` and `schema_name` have replaced `format`.
I've removed some tests rather than updating them, because they duplicated the implementation. The schema tests seem sufficient here.
Related: https://github.com/alphagov/govuk-content-schemas/pull/348
> Use `document_type` and `schema_name`

- db/migrate/20160920172304_add_organisation_content_id_to_users.rb
- db/schema.rb
- spec/models/user_spec.rb
Gds-sso gem version 11.0 introduced the required fields `disabled` and `organisation_content_id`. This was missed when the gem was upgraded to 12.1.0 recently, thereby breaking admin authentication. This commit adds the migration for those two fields.
https://github.com/alphagov/gds-sso/blob/master/CHANGELOG.md#1010-includes-a-breaking-change
> Add `organisation_content_id` string field to User

- Gemfile
- Gemfile.lock
- app/models/contact.rb
- app/models/world_location.rb
- app/presenters/contact_presenter.rb
- app/presenters/post_addresses_presenter.rb
- app/tasks/import_organisations.rb
- config/initializers/gds_api_adapters.rb
- spec/presenters/contact_presenter_spec.rb
- spec/support/mock_organisations_api.rb
- spec/support/shared_contexts/mock_world_location.rb
[Trello card](https://trello.com/c/B5z6Dq8q/)
Some old behaviour has been deprecated in [gds-api-adapters](https://github.com/alphagov/gds-api-adapters) so we are updating this app to comply with this before it becomes the default. Firstly, a GdsApi::NotFound error is now raised when the server returns a 404 or 410.  Secondly, requests now return a hash instead of an OpenStruct.  We have now opted in to this new behaviour.
OpenStructs have been converted to hashes where necessary, and where this data is being accessed has been modified accordingly.  In particular, we have removed delegator methods from WorldLocation and replaced them with separate methods as they are no longer suitable to retrieve title and slug information.
As part of this work, we made a change to gds-api-adapters to …
> Update gds api adapters behaviour

- app/controllers/admin/contact_groups_controller.rb
- app/presenters/contact_rummager_presenter.rb
- app/services/publish_finders.rb
- lib/tasks/publish_finders.rake
- spec/presenters/contact_rummager_presenter_spec.rb
- spec/schemas/finder_schema_validation_spec.rb
- spec/services/publish_finders_spec.rb
This commit migrates the rendering of the HMRC contacts page at https://www.gov.uk/government/organisations/hm-revenue-customs/contact from contacts-admin to finder-frontend, since the formats are so similar.
A service and rake task are provided to publish the finder to the Publishing API. This also happens every time a contact group is added/edited/deleted in the admin interface since the contact groups are included in the JSON that is sent to the Publishing API.
Finally, contact groups are sent to rummager to be indexed so that the finder facets work.
Trello: https://trello.com/c/wD10DEXt/260-migrate-the-hmrc-contacts-page-to-a-finder
Paired with @klssmith 
A follow-up PR will remove the code that renders the current version of the page in this app.
Deployment checklist
> Migrate the HMRC contacts page to finder-frontend

- app/services/publish_finders.rb
- spec/services/publish_finders_spec.rb
This commit sets the parent of the HMRC contacts finder to the HMRC organisation page. This will allow finder-frontend to display the correct breadcrumbs for the finder, once https://github.com/alphagov/finder-frontend/pull/259 has been deployed.
Trello: https://trello.com/c/wD10DEXt/260-migrate-the-hmrc-contacts-page-to-a-finder
Before:
After:
> Set the parent of the HMRC contacts finder

- lib/tasks/publish_finders.rake
This commit aliases the `finders:publish` rake task to `publishing_api:publish`, which allows `govuk-app-deployment` to use an existing `capistrano` task during deployment to run this rake task.
Trello: https://trello.com/c/wD10DEXt/260-migrate-the-hmrc-contacts-page-to-a-finder
> Alias finders:publish rake task

- config/environments/development.rb
- config/environments/test.rb
- config/routes.rb
- lib/contacts.rb
Noe that contacts-admin is a purely admin app with no frontend code, and only deployed to backend servers, we no longer need to disable the admin routes on frontend servers.
> Remove “enable_admin_routes”

- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
contacts-admin currently serves all assets via the assets server. Now that it is no longer a frontend app, assets can be served locally, which also brings it into line with other admin-only apps.
Trello: https://trello.com/c/wD10DEXt/260-migrate-the-hmrc-contacts-page-to-a-finder
> Change assets config to serve all assets locally

- app/presenters/contact_rummager_presenter.rb
We need to be able to filter Rummager on document_type for Guidance content, so this change updates Searchable to present the document type for all "Editions".
This has been tested locally by running the `contacts:republish` Rake task and checking that the `content_store_document_type` was present on a given document.
Trello: https://trello.com/c/M1cXENeB/341-add-content-store-document-type-to-all-guidance-content-in-rummager
> Register Document Type with Rummager

- Jenkinsfile
The job to build this repo in Jenkins is `contacts`. We were previously sending through the wrong job name when deploying to Integration.
> Change repo name in Jenkinsfile

- Jenkinsfile
- spec/presenters/contact_presenter_spec.rb
- spec/presenters/contact_rummager_presenter_spec.rb
While working on contacts admin, it turned out that the tests are not running on jenkins :man_facepalming: and there was some broken tests, this re enables jenkins running the tests and fixes the broken tests
example of tests not running
https://ci.integration.publishing.service.gov.uk/job/contacts/job/change-rendering-app/3/
with this branch
https://ci.integration.publishing.service.gov.uk/job/contacts/job/fix-broken-tests-on-master/1/
https://trello.com/c/pIBrqrZX
> Fix broken tests on master and enable Jenkins to run the tests

- app/presenters/contact_presenter.rb
- app/services/publish_finders.rb
- spec/presenters/contact_presenter_spec.rb
This adds in the parent link, this is hardcoded currently in
government frontend, this pull should enable us to do it in
the standard govuk way
> Add in parent link for the generation of links government frontend

- Gemfile
- Gemfile.lock
- app/lib/publisher.rb
- app/presenters/contact_gone_presenter.rb
- app/presenters/contact_presenter.rb
- app/presenters/contact_redirect_presenter.rb
- app/services/publish_finders.rb
- config/initializers/gds_api_adapters.rb
- spec/lib/publisher_spec.rb
- spec/services/publish_finders_spec.rb
Sending it on publish has been deprecated in favour of including it when sending a put content.
[Trello Card](https://trello.com/c/LnJlkb9e/987-5-deprecate-the-usage-of-updatetype-in-publish-for-publishing-api-and-update-usage-across-govuk)
> Send update type with put content

- app/lib/publisher.rb
- spec/lib/publisher_spec.rb
The second argument is update_type, so if we're not going to be using it, we need to set it to `nil`.
> Call publishing_api.publish correctly

- Gemfile
- Gemfile.lock
- app/lib/publisher.rb
- spec/lib/publisher_spec.rb
We're moving away from Errbit because it's an unsupported fork, isn't
meeting our needs very well and complicates the move to AWS. We're going
for Sentry because most people seem to like it, used by other teams in
GDS, it's modern and up-to-date and we can use a SaaS version.
https://trello.com/c/DJ7h8C1b/306-make-sure-the-apps-we-support-are-migrated-to-sentry
https://trello.com/c/TvhWdRDI/40-update-contacts-admin
Paired with @Rosa-Fox
> Replace Airbrake monitoring with Sentry

- app/presenters/contact_presenter.rb
- spec/presenters/contact_presenter_spec.rb
[Trello](https://trello.com/c/KX2WILnc/332-add-contactgroups-to-publishing-api)
- Part of the work to migrate contacts_admin to use the govuk_index.
- Previously publishing-api did not have the contact_groups fields.
- They are now needed so that publishing-api can send them to Rummager, as opposed to contacts-admin sending them straight to Rummager.
Depends on [this change](https://github.com/alphagov/govuk-content-schemas/commit/a20b6ae73d0f9668b2e026dd2a653bd4a02c241e) to content-schemas being deployed.
Paired with @suzannehamilton.
> Send contact_groups to the publishing-api

- app/views/admin/shared/_formatting.html.erb
For: https://trello.com/c/M45WyUGZ/261-retire-design-principles
That route has been retired in favour of a new one and we might as well
save a redirect.
> Stop talking about the design principles style guide

- Jenkinsfile
Hey :wave: !
This PR will enable a set of [end-to-end tests](https://github.com/alphagov/publishing-e2e-tests) to run every time a commit is made to this repo. :boom:
You can read through the scenarios at a [high level](https://docs.google.com/document/d/1llMC5n-sKZJwmK0lbsm3QpTRn9yjjLi1ECVDVyiKGNI/edit?usp=sharing), and the capybara [here](https://github.com/alphagov/publishing-e2e-tests/tree/master/spec/contacts).
Look at the merge box below and you'll see a new check performed on this PR.
Enabling these tests will give increased confidence when making changes to this repo that the change doesn't break the publisher in an end-to-end environment. The downside is that running these tests takes time, with build times between 6-8 minutes currently.
> Run contacts-admin end to end tests downstream job as part of CI

- app/services/publish_finders.rb
Good services are verbs. This makes the title consistent with the current breadcrumbs on the contact pages itself. Needed if we want to keep the breadcrumb the same after https://github.com/alphagov/government-frontend/pull/837.
Signed off by Ganesh.
https://trello.com/c/1LEofaHC
> Rename the finder to "Contact HM Revenue & Customs"

- config/initializers/new_framework_defaults.rb
`false` is the default value in Rails 5.0 / 5.1, and this option is no
longer supported in Rails 5.2.  Rails 5.2 has the same behaviour as
setting this to `false` in Rails 5.0 / 5.1.
For more, see https://blog.bigbinary.com/2016/02/13/rails-5-does-not-halt-callback-chain-when-false-is-returned.html
> Remove no-op configuration option

- app/presenters/contact_presenter.rb
- spec/presenters/contact_presenter_spec.rb
This field has been replaced by the `meets_user_needs` link type.
> Remove code related to need_ids

- app/interactors/admin/destroy_and_redirect_contact.rb
- spec/interactors/admin/destroy_and_redirect_contact_spec.rb
Use the unpublish action in the Publishing API, rather than replacing
the content with a redirect.
> Improve DestroyAndRedirectContact

- app/controllers/admin/contacts_controller.rb
- app/presenters/contact_presenter.rb
- app/tasks/import_contacts/contact_builder.rb
- app/views/admin/contacts/_form.html.erb
- db/migrate/20180723102908_add_more_info_webchat_to_contacts.rb
- db/schema.rb
This commit adds a more info field for the webchat section of a contact. This allows non-developers to change this text, which was previously hardcoded into government-frontend.
Depends on https://github.com/alphagov/govuk-content-schemas/pull/798
Trello: https://trello.com/c/kcGo8LWv/331-webchats-changes-to-dynamic-text
> Add more info field for webchat

- app/controllers/healthcheck_controller.rb
- config/routes.rb
This uses the standard healthcheck endpoint from GovukAppConfig.
The hope is that this will prevent odd healthcheck errors in Sentry:
https://sentry.io/govuk/app-contacts-admin/issues/736044917
https://trello.com/c/CxGTjfcH
> Use standard healtcheck

- Gemfile
- Gemfile.lock
- Jenkinsfile
- app/tasks/import_organisations.rb
Another attempt to get e2e-tests working again since https://github.com/alphagov/contacts-admin/pull/498 didn't do the job.
/cc @theseanything @cbaines
> Revert "Bump gds-api-adapters from 53.2.0 to 54.1.2"

- app/interactors/admin/create_contact.rb
- lib/tasks/contacts.rake
- spec/features/admin/contact_create_spec.rb
At present only `organisations` are sent to the publishing-api
(via patch_links) when a contact is published.
This commit also includes `primary_publishing_organisation` in the payload sent 
to `publishing-api`.
We need this information to be available in the `content-data-api`
so we can filter based on it.
Trello: https://trello.com/c/Vsdvr5vb/1390-add-primary-org-to-contacts
> Present primary publishing organisation

- spec/features/admin/contact_create_spec.rb
- spec/features/admin/contact_edit_spec.rb
Change to using strings, rather than objects with the select function.
This avoids deprecation warnings like:
Locator ContactGroup:#<ContactGroup id: 212, contact_group_type_id:
13, title: "new contact type", description: "contact group description
12", contacts_count: nil, created_at: "2019-07-09 10:06:24",
updated_at: "2019-07-09 10:06:24", slug: "new-contact-type",
organisation_id: 494> for selector :option must be an instance of
String or Symbol. This will raise an error in a future version of
Capybara.
> Avoid a Capybara deprecation warning

- Rakefile
The README suggests this is the case, but it isn't. This commit
changes that!
> Run rspec as the default Rake task

- Dockerfile
As the build fails without it.
> Set GOVUK_WEBSITE_ROOT in the Dockerfile

- config/initializers/assets.rb
There seems to be issues with Sprockets version 4, errors like [1]
occur when precompiling assets.
A suggestion I've seen to avoid this is to add this configuration [2].
1: SassC::SyntaxError: Error: error in C function font-path: undefined
method `[]' for nil:NilClass
2: https://github.com/rails/sprockets/issues/581#issuecomment-486984663
> Set assets.export_concurrent to false

- Gemfile.lock
This might help with some issues we're having with sassc since the
Sprockets 4 update. Note that I've had problems builing the native
extensions with gcc > 4.
> Change sassc to 2.2.1 in the Gemfile.lock

- app/presenters/contact_presenter.rb
- app/services/publish_finders.rb
- spec/factories/contacts.rb
- spec/factories/organisations.rb
- spec/presenters/contact_presenter_spec.rb
Previously it was assumed that HMRC would be the only organisation for which contacts would be published for. When a new contact was created, links sent to the publishing API contained hardcoded references to HMRC's contacts finder. 
This PR changes the parent link to be the contacts organisations id, unless it is HMRC then it remains as the HMRC contacts finder. 
This is needed to publish an non-HMRC contact page, (relating to the web chat work.)
> Fix hardcoded HMRC organisation used for all contacts

- .rubocop.yml
- Gemfile
- Gemfile.lock
- bin/bundle
- bin/rails
- bin/rake
- bin/setup
- bin/update
- lib/tasks/lint.rake
- Fixes existing linting issues
- The GOV.UK Lint gem is deprecated in favour of using Rubocop directly
with a set of shared configs.
- See https://github.com/alphagov/govuk-rfcs/pull/ 100 for more context.
https://trello.com/c/CdBFg6yw/1521-replace-govuk-lint-with-rubocop-govuk
> Replace `govuk-lint`

- lib/tasks/lint.rake
Rubocop cannot run in production.  Prior art:
- https://github.com/alphagov/travel-advice-publisher/pull/755/commits/1f94be85f9eb8116034e7042b214a9384de0d5ff
- https://github.com/alphagov/asset-manager/commit/a7ff35d2210575dace952bd686d7eda11c8b44f3
Also flipped to the new style of task declaration as it seems nicer.
> Fix deployment errors due to rubocop rake task

- app/models/contact.rb
The `destroy` method fails with
```
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 
'contact_relationships.' in 'where clause': DELETE FROM `contact_relationships` 
WHERE `contact_relationships`.`` IS NULL
```
This is because contact_relationships table doesn't have a primary key.
When we use `dependent: :destroy` rails tries to instantiate each dependent model which is impossible without a primary key. 
We should to use `dependent: :delete_all` so rails doesn't initialise any dependent models.
Zendesk ticket: https://govuk.zendesk.com/agent/tickets/3867768
---
Tested in integration:
> Use delete_all method to remove contact relationships

- Gemfile.lock
- app/lib/services.rb
To simplify the migration of Whitehall to AWS, calls to the Worldwide
API should be directed to whitehall-frontend, not whitehall-admin.
Co-authored-by: Christopher Baines <christopher.baines@digital.cabinet-office.gov.uk>
> [DO NOT MERGE BEFORE alphagov/govuk-puppet#10054] Access Worldwide API via whitehall-frontend

- .rubocop.yml
- Gemfile
- Rakefile
- app/helpers/application_helper.rb
- config/initializers/simple_form_bootstrap.rb
- lib/tasks/lint.rake
https://trello.com/c/5Gob6WUL/147-ensure-that-rubocop-runs-as-part-of-bundle-exec-rake-as-one-of-the-default-tasks
This adds a new 'lint' rake task that runs as part of a default call to
'rake'. Having linting run locally by default makes it easier to catch
build issues, and is a prerequisite for moving to GitHub Actions, since we
want to avoid listing lots of separate build steps.
> Extend 'default' task with RuboCop linting

- Gemfile.lock
- app/tasks/import_contacts.rb
These are the changes necessary for Ruby 2.7.1
There is a script that can be run to update all app Ruby versions at once, so leaving the Ruby version as 2.6.6 in this PR.
> Upgrade to ruby 2.7.1

- Gemfile
- Gemfile.lock
- spec/rails_helper.rb
https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
Note that RCov is just an optional formatter. We can still see a
detailed webpage of coverage without it.
> Always print coverage after running tests

- Dockerfile
- app/lib/contacts/distributed_lock.rb
Trello: https://trello.com/c/dXud4WIt/206-inconsistent-redisurl-config
This is one of the few GOV.UK projects that uses this old approach to
configuring Redis - whereas most of the other ones use the approach
supported natively by the Redis gem [1] of using REDIS_URL. Removing
this will allow us to remove the need for REDIS_HOST and REDIS_PORT env
vars in our architecture and also allows this code to be simplified.
[1]: https://github.com/redis/redis-rb
> Remove need for REDIS_HOST and REDIS_PORT env vars

- app/services/publish_finders.rb
We are currently building a Search API query based on the content of the `filter` hash within the content item when fetching contact details.
However we aren't filtering by organisation, so all organisation results are being returned on the HMRC contact page, rather than only their own.
This can be tested by changing the Search API query, e.g.
https://www.gov.uk/api/search.json?filter_format=contact (141 results, which include two HM Passport Office contacts)
https://www.gov.uk/api/search.json?filter_format=contact&filter_organisations=hm-revenue-customs (139 results, which does not include the HMPO contacts)
After merging, the content item will need updating using `rake finders:publish`.
Zendesk ticket: https://govuk.zendesk.com/agent/tickets/4408921
> Add filter to content item for HM Revenue & Customs

- README.md
On further investigation, CRUD operations don't seem to need
Publishing API running in another shell, and will work after
enough refreshes.
> Clarify govuk-docker troubleshooting tips

- README.md
- lib/tasks/contacts.rake
This is now the default behaviour as of #838, so should never have to be invoked by a developer again.
> Remove unused Rake task

- README.md
- docs/redirects.md
- startup.sh
https://trello.com/c/Psf7EzPB/204-move-away-from-startupsh
This makes several changes to refactor and revise the README to
better match our other repos. The end result follows the pattern
established in [1]. Please see the commit messages for more details.
[1]: alphagov/content-publisher#2257
> Revise tech docs in README to favour GOV.UK Docker

- app/controllers/admin/contacts_controller.rb
This polymorphic route was generating an error due to the tab param
being a sting `Please use symbols for polymorphic route arguments.`.
I've also had a gander at the rest of the app and didn't spot any more
occurrences of strings in these route types.
Sentry error: https://sentry.io/organizations/govuk/issues/2501896125/?project=202215&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+none%5D&sort=inbox 
As reported by a Zendesk user: https://govuk.zendesk.com/agent/tickets/4607154
> Fix polymorphic path bug

- spec/models/post_address_spec.rb
- spec/presenters/post_addresses_presenter_spec.rb
- spec/rails_helper.rb
We're intermittently - but regularly - seeing the following tests
fail:
```
rspec ./spec/models/post_address_spec.rb:5 # PostAddress behaves like an associated data model registers its parent contact on save
rspec ./spec/presenters/post_addresses_presenter_spec.rb:8 # PostAddressesPresenter transforms a contact to the correct format
```
They both have the same error:
```
Failure/Error:
Services
.worldwide_api
.world_location(location_slug)
.parsed_content
WebMock::NetConnectNotAllowedError:
Real HTTP connections are disabled. Unregistered request: GET http://www.dev.gov.uk/api/world-locations/united-kingdom with headers {'Accept'=>'application/json', 'Accept-Encoding'=>'gzip;q=1.0,deflate;q=0.6,identity;q=0.3', 'Host'=>'www.dev.gov.uk', 'User-Agent'=>'gds-api-adapters/71.5.0 ()'}
You can …
```
> Fix Contacts test

- Jenkinsfile
This changes the Jenkins CI configuration to use MySQL 8.
MySQL is [available at port `33068 `](https://docs.publishing.service.gov.uk/manual/test-and-build-a-project-on-jenkins-ci.html#specifying-which-database-to-use) on the CI server. By explicitly setting the `TEST_DATABASE_URL`, we're telling Rails to use that MySQL server.
Previously, Rails implicitly used the default MySQL port `3306` which is a MySQL 5.5 server.
Trello ticket: https://trello.com/c/btcm7JyB/
The database config is already using the correct ENV var
> Upgrade CI to use MySQL 8

- Jenkinsfile
- app/tasks/seed_database.rb
- db/seeds.rb
ImportOrganisations.new.call involves pulling data dynamically in from
GOV.UK. This makes it an extremely complicated approach to seeding a
database, and causes a bunch of misery in spinning up a production-like
environment for GOV.UK (as is the case with publishing_e2e_tests [1]) as
you need Whitehall to have published data, that data to make it to
Search API, Router to be running and then Collections running - a heck
of a lot for a db:seed!
It's unclear why this is needed, the SeedDatabase step will create a
single organisation (HMRC) which is probably all that is needed.
This simplifies this just to the more basic seed call.
> Remove import organisations from db:seed

- app/lib/contacts.rb
Removing a file that is redundant. Contacts was replaced by Services in [this PR ](https://github.com/alphagov/contacts-admin/commit/437a78aa27f550d4da11bace78dee99d6638ee6c) but it looks like we forgot to remove the contacts.rb file.
> Remove unused contacts file

- config/application.rb
This has now been deployed to production for a number of weeks, therefore we can remove the code to rotate the cookies that was added in bb4b1653d7bce360a30532c6061c99ae39d43e3f.
[Trello card](https://trello.com/c/nmJc03Gd/249-upgrade-contacts-admin-from-rails-61x-to-70x)
> Remove SHA1 to SHA256 cookie rotation

- app/lib/contacts/distributed_lock.rb
- spec/lib/contacts/distributed_lock_spec.rb
Redis.current will be deprecated in Redis 5.0.
As Redis.current ultimately calls Redis.new we can migrate this method now to pave the way for future upgrades.
From Redis changelog from [5.0][1]:
‘Removed Redis.current. You shouldn't assume there is a single global Redis connection, use a connection pool instead, and libaries using Redis should accept a Redis instance (or connection pool) as a config. E.g. MyLibrary.redis = Redis.new(…).’
[Redis.current][2] just calls Redis.new so should just be able to swap methods.
[trello](https://trello.com/c/oGFWhrCO/1551-migrate-away-from-deprecated-redis-method)
> Use Redis.new rather than Redis.current

- Jenkinsfile
Having this after build project meant that this had no effect and the local version of MySQL was used
> Move Jenkinsfile env var so it has an effect

- .dockerignore
- Dockerfile
- Parameterise the Ruby version.
- Precompute the [bootsnap](https://github.com/Shopify/bootsnap#bootsnap-) bytecode and path caches so that bootsnap is effective when running the app from the container image.
- Remove some hard-coded paths.
- Clean up `.dockerignore`.
- Make better use of `WORKDIR`.
- Remove the now-redundant `bundle exec` from the default command.
Tested: builds and comes up healthy on the integration Kubernetes cluster.
> Clean up Dockerfile.

- Gemfile.lock
- app/models/world_location.rb
- spec/interactors/admin/clone_contact_spec.rb
- spec/models/post_address_spec.rb
- spec/models/world_location_spec.rb
- spec/presenters/post_addresses_presenter_spec.rb
- spec/rails_helper.rb
This version of `gds-api-adapters` removes pagination of the world locations, so we need to update this application accordingly.
[Trello card](https://trello.com/c/4r5uSD2R)
> Update world location code for breaking changes in `gds-api-adapters` version 89.0.0

- app/views/layouts/admin.html.erb
- config/initializers/sha.rb
This has been broken since we moved to EKS and the SHA is no longer provided.
We can use the [SENTRY_RELEASE](https://github.com/alphagov/govuk-helm-charts/blob/077117e7f40c096a958f9e0b853a2bd76cf43f26/charts/generic-govuk-app/templates/deployment.yaml#L92C1-L92C1) environment variable which is defined for every app and takes its value from the container image's tag.
If for whatever reason the image tag is not defined it will display `null`, which should make it clearer (instead of displaying `development`) that this data is not being pulled in successfully.
Trello card: https://trello.com/c/uoKDUcbV/3182-fix-broken-version-footer-in-publishing-apps-2
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipelin …
> Fix release version in footer

- Gemfile
- Gemfile.lock
- app/views/layouts/_google_tag_manager.html.erb
- app/views/layouts/admin.html.erb
Google Tag Manager (GTM) can be included on all pages of the app by configuring the following environment variables:
GOOGLE_TAG_MANAGER_ID
GOOGLE_TAG_MANAGER_AUTH
GOOGLE_TAG_MANAGER_PREVIEW
All three variables are optional.
If none are set, GTM will not be included on the page.
If only GOOGLE_TAG_MANAGER_ID is set, the default environment of the GTM container will be used.
If GOOGLE_TAG_MANAGER_AUTH and GOOGLE_TAG_MANAGER_PREVIEW are set, the specified GTM container environment will be used. This is used for managing the rollout of changes to integration so they can be tested before rolling out to production.
Trello card: https://trello.com/c/Wcuq3R1S/2167-add-ga4-page-view-tracking-to-apps-that-we-own
> Add Google Tag Manager snippet

- .gitignore
- Gemfile
- Gemfile.lock
- app/assets/config/manifest.js
- config/environments/production.rb
- config/initializers/dartsass.rb
LibSass has been deprecated. We're moving to Dart Sass. This follows the upgrade guide found here
https://docs.publishing.service.gov.uk/manual/migrate-to-dart-sass-from-libsass.html
I've deployed and tested this on integration.
https://trello.com/c/qeNHFPZN/1667-migrate-to-dart-sass
> Migrate to dartsass

- Gemfile
- Gemfile.lock
Despite the tests passing in #1439, the deployment failed in https://github.com/alphagov/contacts-admin/actions/runs/10166486149 with:
```
[builder 7/7] RUN rails assets:precompile && rm -fr log
0.106 INFO: with_tmpdir_for_ruby: execing rails with TMPDIR=/tmp/ruby-app-xGCNAKnA
1.525 I, [2024-07-30T17:53:13.769638 #7]  INFO -- : govuk_app_config changing time_zone from UTC (the default) to London
10.13 bin/rails aborted!
10.13 Uglifier::Error: Name expected (Uglifier::Error)
10.13 --
10.13  33111   window.GOVUK.modules.start()
10.13  33112 });
10.13  33113 (function (global, factory) {
10.13  33114   typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
10.13  33115   typeof define === 'function' && define.amd ? define(['exports'], factory) :
10.13  33116 …
```
> Revert govuk_publishing_components major version bump

- Gemfile
- Gemfile.lock
- config/environments/production.rb
This is effectively an upgrade to GOV.UK Frontend 5.
This is another attempt at making the upgrade. We've just reverted in [PR #1467](https://github.com/alphagov/contacts-admin/pull/1467). 
Current changes include replacing `Uglifier` with `Terser` as per the documentation [here](https://docs.google.com/document/d/1uwip7pzQwM7t5ghn9_8KrsWXLePSRUltFPZ5fYw6Ab8/edit).
> Upgrade to govuk_publishing_components 43.1.1

- app/services/publish_finders.rb
See https://github.com/alphagov/specialist-publisher/pull/2998
Trello: https://trello.com/c/ZiFU2o6B
> Remove unused `format_name` property
